apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-timeout-app
  namespace: default
  labels:
     app: test-timeout-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-timeout-app
  template:
    metadata:
      labels:
        app: test-timeout-app
    spec:
      containers:
      - name: test-timeout-app
        image: us.icr.io/openshift-tests-paz/test-timeout-app:v1
        ports:
          - containerPort: 8080
        env:
          - name: TIMEOUT
            value: "60000"
---
apiVersion: v1
kind: Service
metadata:
  name: service-test-timeout-app
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: test-timeout-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: route-test-timeout-app
    namespace: default
spec:
    to:
        kind: Service
        name: service-test-timeout-app
